import { z } from "zod";

const envSchema = z.object({
  APP_URL: z.string().url().default("http://localhost:3000"),
  NODE_ENV: z.enum(["development", "production", "test"]).default("development"),
  DATABASE_URL: z.string().min(1),
  REDIS_URL: z.string().default("redis://localhost:6379"),
  SESSION_SECRET: z.string().min(32),
  ENCRYPTION_KEY: z.string().length(64),
  SHOPIFY_API_KEY: z.string().min(1),
  SHOPIFY_API_SECRET: z.string().min(1),
  SHOPIFY_SHOP_DOMAIN: z.string().optional(),
  SHOPIFY_ADMIN_ACCESS_TOKEN: z.string().optional(),
  SHOPIFY_WEBHOOK_SECRET: z.string().optional(),
  SHOPIFY_SCOPES: z.string().default(
    "read_products,read_orders,write_orders,read_inventory,read_customers,write_draft_orders,read_locations"
  ),
  SHOPIFY_API_VERSION: z.string().default("2026-01"),
  ADMIN_PASSWORD: z.string().min(12).optional(),
  INTERNAL_JOBS_SECRET: z.string().min(16),
  SENTRY_DSN: z.string().optional(),
  NOVA_POSHTA_API_KEY: z.string().optional(),
  CHECKBOX_API_URL: z.string().url().default("https://api.checkbox.in.ua/api/v1"),
  SUPABASE_URL: z.string().url().optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
  SUPABASE_ANON_KEY: z.string().optional(),
  SUPABASE_DOCUMENTS_BUCKET: z.string().default("b2b-documents"),
  RESEND_API_KEY: z.string().optional(),
  DOCUMENTS_FROM_EMAIL: z.string().email().optional(),
  SELLER_NAME: z.string().optional(),
  SELLER_TAX_ID: z.string().optional(),
  SELLER_IBAN: z.string().optional(),
  SELLER_BANK_NAME: z.string().optional(),
  SELLER_LEGAL_ADDRESS: z.string().optional(),
  SELLER_PHONE: z.string().optional(),
  SELLER_SIGNATURE_NAME: z.string().optional(),
  BANK_PROVIDER: z.enum(["mock", "csv", "privatbank"]).default("mock"),
  BANK_API_URL: z.string().url().optional(),
  BANK_API_TOKEN: z.string().optional(),
  BANK_ACCOUNT_IBAN: z.string().optional(),
  FISCALIZATION_PROVIDER: z.enum(["noop", "checkbox", "wayforpay_prro"]).default("noop"),
  CHECKBOX_API_KEY: z.string().optional(),
  WAYFORPAY_MERCHANT_ACCOUNT: z.string().optional(),
  WAYFORPAY_SECRET_KEY: z.string().optional(),
  ACCOUNTING_PROVIDER: z.enum(["none", "diloshop", "dilovod", "bas"]).default("none"),
  DILOSHOP_API_URL: z.string().url().optional(),
  DILOSHOP_API_KEY: z.string().optional(),
  DILOSHOP_WEBHOOK_URL: z.string().url().optional(),
  DILOSHOP_NP_WEBHOOK_URL: z.string().url().optional(),
  DILOSHOP_NP_FLOW_SECRET: z.string().optional(),
  DILOSHOP_WEBHOOK_SECRET: z.string().optional(),
  DILOVOD_API_URL: z.string().url().optional(),
  DILOVOD_API_KEY: z.string().optional(),
  CRON_SECRET: z.string().optional(),
});

export type Env = z.infer<typeof envSchema>;

let cached: Env | null = null;

export function getEnv(): Env {
  if (cached) return cached;
  cached = envSchema.parse({
    APP_URL: process.env.APP_URL,
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URL:
      process.env.DATABASE_URL ||
      process.env.POSTGRES_PRISMA_URL ||
      process.env.POSTGRES_URL ||
      process.env.POSTGRES_URL_NON_POOLING,
    REDIS_URL: process.env.REDIS_URL,
    SESSION_SECRET: process.env.SESSION_SECRET,
    ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
    SHOPIFY_API_KEY: process.env.SHOPIFY_API_KEY,
    SHOPIFY_API_SECRET: process.env.SHOPIFY_API_SECRET,
    SHOPIFY_SHOP_DOMAIN: process.env.SHOPIFY_SHOP_DOMAIN,
    SHOPIFY_ADMIN_ACCESS_TOKEN: process.env.SHOPIFY_ADMIN_ACCESS_TOKEN,
    SHOPIFY_WEBHOOK_SECRET: process.env.SHOPIFY_WEBHOOK_SECRET,
    SHOPIFY_SCOPES: process.env.SHOPIFY_SCOPES,
    SHOPIFY_API_VERSION: process.env.SHOPIFY_API_VERSION,
    ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
    INTERNAL_JOBS_SECRET: process.env.INTERNAL_JOBS_SECRET,
    SENTRY_DSN: process.env.SENTRY_DSN,
    NOVA_POSHTA_API_KEY: process.env.NOVA_POSHTA_API_KEY,
    CHECKBOX_API_URL: process.env.CHECKBOX_API_URL,
    SUPABASE_URL: process.env.SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY,
    SUPABASE_DOCUMENTS_BUCKET: process.env.SUPABASE_DOCUMENTS_BUCKET,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    DOCUMENTS_FROM_EMAIL: process.env.DOCUMENTS_FROM_EMAIL,
    SELLER_NAME: process.env.SELLER_NAME,
    SELLER_TAX_ID: process.env.SELLER_TAX_ID,
    SELLER_IBAN: process.env.SELLER_IBAN,
    SELLER_BANK_NAME: process.env.SELLER_BANK_NAME,
    SELLER_LEGAL_ADDRESS: process.env.SELLER_LEGAL_ADDRESS,
    SELLER_PHONE: process.env.SELLER_PHONE,
    SELLER_SIGNATURE_NAME: process.env.SELLER_SIGNATURE_NAME,
    BANK_PROVIDER: process.env.BANK_PROVIDER,
    BANK_API_URL: process.env.BANK_API_URL,
    BANK_API_TOKEN: process.env.BANK_API_TOKEN,
    BANK_ACCOUNT_IBAN: process.env.BANK_ACCOUNT_IBAN,
    FISCALIZATION_PROVIDER: process.env.FISCALIZATION_PROVIDER,
    CHECKBOX_API_KEY: process.env.CHECKBOX_API_KEY,
    WAYFORPAY_MERCHANT_ACCOUNT: process.env.WAYFORPAY_MERCHANT_ACCOUNT,
    WAYFORPAY_SECRET_KEY: process.env.WAYFORPAY_SECRET_KEY,
    ACCOUNTING_PROVIDER: process.env.ACCOUNTING_PROVIDER,
    DILOSHOP_API_URL: process.env.DILOSHOP_API_URL,
    DILOSHOP_API_KEY: process.env.DILOSHOP_API_KEY,
    DILOSHOP_WEBHOOK_URL: process.env.DILOSHOP_WEBHOOK_URL,
    DILOSHOP_NP_WEBHOOK_URL: process.env.DILOSHOP_NP_WEBHOOK_URL,
    DILOSHOP_NP_FLOW_SECRET: process.env.DILOSHOP_NP_FLOW_SECRET,
    DILOSHOP_WEBHOOK_SECRET: process.env.DILOSHOP_WEBHOOK_SECRET,
    DILOVOD_API_URL: process.env.DILOVOD_API_URL,
    DILOVOD_API_KEY: process.env.DILOVOD_API_KEY,
    CRON_SECRET: process.env.CRON_SECRET,
  });
  return cached;
}
